---
driver:
  name: vagrant
  vagrantfile_erb: test/integration/Vagrantfile.erb

provisioner:
  name: chef_zero
  client_rb:
    environment: stage
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/.chef/encrypted_data_bag_secret  

platforms:
- name: ubuntu-12.04
  driver_config:
    customize:
      cpus: 4
      memory: 1536
      addl_volumes: 2

suites:
- name: namenode
  driver_config:
    network:
    - [ 'private_network', {ip: '192.168.33.10'}]
  attributes: {}
  run_list: [
    'recipe[et_hostname]',
    'recipe[apt]',
    'recipe[et_tools]',
    'recipe[et_networking_basic]',
    'recipe[et_hadoop::namenode]',
    'recipe[continuuity_hadoop::hadoop_yarn_resourcemanager]'
  ]
- name: datanode
  driver_config:
    network:
    - [ 'private_network', {ip: '192.168.33.11'}]
  attributes: {}
  run_list: [
    'recipe[et_hostname]',
    'recipe[apt]',
    'recipe[et_tools]',
    'recipe[et_networking_basic]',
    'recipe[et_hadoop::datanode]',
    'recipe[continuuity_hadoop::hadoop_yarn_nodemanager]'
  ]
