---
driver:
  name: vagrant
  require_chef_omnibus: true
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/.chef/encrypted_data_bag_secret

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-12.04
  driver_config:
    customize:
      cpus: 4
      memory: 1536

suites:
- name: default
  run_list: [
    'recipe[et_hadoop::namenode]',
    'recipe[et_hadoop::jobtracker]',
    'role[namenode]',
    'role[jobtracker]'
  ]
