---
driver:
  name: ec2
  require_chef_omnibus: true
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  username: ubuntu
  flavor_id: c3.large
  interface: public

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/encrypted_data_bag_secret
  client_rb:
    environment: dev

platforms:
- name: ubuntu-12.04
  driver_config:
    tags:
      Name: vagrant-et-hadoop-1204
      Env: public
    customize:
      cpus: 4
      memory: 1536
      addl_volumes: 2

suites:
- name: namenode
  attributes:
    hadoop:
      force_format: true
      cluster_name: main
      yarn_site:
        yarn.resourcemanager.scheduler.address: 0.0.0.0
        yarn.resourcemanager.resource-tracker.address: 0.0.0.0
        yarn.resourcemanager.admin.address: 0.0.0.0
        yarn.resourcemanager.webapp.address: 0.0.0.0
        yarn.resourcemanager.address: 0.0.0.0
      core_site:
        fs.defaultFS: 'hdfs://0.0.0.0/'
      hosts:
        namenode: namenode-ubuntu-1204.priv.evertrue.com
    et_hostname:
      addl_hosts_entries:
        - '10.140.167.9 namenode-ubuntu-1204.vagrantup.com namenode-ubuntu-1204'
        - '10.231.6.185 datanode-ubuntu-1204.vagrantup.com datanode-ubuntu-1204'
  run_list: [
    'recipe[et_hostname]',
    'recipe[apt]',
    'recipe[et_tools]',
    'recipe[et_networking_basic]',
    'recipe[et_hadoop::namenode]',
    'recipe[continuuity_hadoop::hadoop_yarn_resourcemanager]'
  ]
- name: datanode
  attributes:
    hadoop:
      yarn_site:
        yarn.nodemanager.localizer.address: 0.0.0.0
        yarn.nodemanager.webapp.address: 0.0.0.0
        yarn.nodemanager.address: 0.0.0.0
      cluster_name: main
    et_hostname:
      addl_hosts_entries: 
        - '10.140.167.9 namenode-ubuntu-1204.vagrantup.com namenode-ubuntu-1204'
        - '10.231.6.185 datanode-ubuntu-1204.vagrantup.com datanode-ubuntu-1204'
  run_list: [
    'recipe[et_hostname]',
    'recipe[apt]',
    'recipe[et_tools]',
    'recipe[et_networking_basic]',
    'recipe[et_hadoop::datanode]',
    'recipe[continuuity_hadoop::hadoop_yarn_nodemanager]'
  ]
