---
driver:
  name: vagrant
  vagrantfile_erb: test/integration/Vagrantfile.erb

provisioner:
  name: chef_zero
  client_rb:
    environment: stage
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/.chef/encrypted_data_bag_secret  

platforms:
- name: ubuntu-12.04
  driver_config:
    customize:
      cpus: 4
      memory: 1536
      addl_volumes: 2

suites:
- name: namenode
  driver_config:
    network:
    - [ 'private_network', {ip: '192.168.33.10'}]
  attributes:
    hadoop:
      force_format: true
      cluster_name: main
      yarn_site:
        yarn.resourcemanager.scheduler.address: 0.0.0.0
        yarn.resourcemanager.resource-tracker.address: 0.0.0.0
        yarn.resourcemanager.admin.address: 0.0.0.0
        yarn.resourcemanager.webapp.address: 0.0.0.0
        yarn.resourcemanager.address: 0.0.0.0
      core_site:
        fs.defaultFS: 'hdfs://0.0.0.0/'
    et_hostname:
      addl_hosts_entries:
        - '192.168.33.11 datanode-ubuntu-1204.vagrantup.com datanode-ubuntu-1204'
        - '192.168.33.10 namenode-ubuntu-1204.vagrantup.com namenode-ubuntu-1204'
  run_list: [
    'recipe[et_hostname]',
    'recipe[apt]',
    'recipe[et_tools]',
    'recipe[et_networking_basic]',
    'recipe[et_hadoop::namenode]',
    'recipe[continuuity_hadoop::hadoop_yarn_resourcemanager]'
  ]
- name: datanode
  driver_config:
    network:
    - [ 'private_network', {ip: '192.168.33.11'}]
  attributes:
    hadoop:
      yarn_site:
        yarn.nodemanager.localizer.address: 0.0.0.0
        yarn.nodemanager.webapp.address: 0.0.0.0
        yarn.nodemanager.address: 0.0.0.0
      cluster_name: main
    et_hostname:
      addl_hosts_entries:
        - '192.168.33.10 namenode-ubuntu-1204.vagrantup.com namenode-ubuntu-1204'
        - '192.168.33.11 datanode-ubuntu-1204.vagrantup.com datanode-ubuntu-1204'
  run_list: [
    'recipe[et_hostname]',
    'recipe[apt]',
    'recipe[et_tools]',
    'recipe[et_networking_basic]',
    'recipe[et_hadoop::datanode]',
    'recipe[continuuity_hadoop::hadoop_yarn_nodemanager]'
  ]
